
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tamojit9
 */
public class image extends javax.swing.JPanel {
    BufferedImage img;
    
    void setImg(String url) {
        try {
           // System.out.println("Enters");
            img =ImageIO.read(new URL(url));
            repaint();
        } catch (MalformedURLException ex) {
            Logger.getLogger(image.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(image.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form image
     */
    public image() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(255, 255, 255)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2) {
            ImagePanel.activeImg = img;
            ImagePanel.shouldRepaint = true;
            
        } else {
            if(ImagePanel.activeImg != null) {
            int cx = getWidth()>>1, cy = getHeight()>>1;
            int width = ImagePanel.activeImg.getWidth(), height = ImagePanel.activeImg.getHeight();
            Rectangle img = new Rectangle(cx-(width>>1), cy-(height>>1), width, height);
            if(!img.contains(evt.getPoint()))  {
                ImagePanel.activeImg = null;
                ImagePanel.shouldRepaint = true;
            }
        }
        }
    }//GEN-LAST:event_formMouseClicked
    
    @Override
    public void paint(Graphics g) {
        super.paintBorder(g);
        Graphics2D g2d = (Graphics2D) g;
        if(img != null) {
            g2d.drawImage(img, 0, 0, getWidth(), getHeight(),null);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
