/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Facebook;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author Tamojit9
 */
public class loading extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form loading
     */
    public loading() {
        initComponents();
        x = getLocation().x;
        y = getLocation().y;
    }
    
    int blue = 152;
    int x, y;
    boolean stop = false;

    public void setStop(boolean stop) {
        this.stop = stop;
    }
    
    
    public void animate() {
        new Thread(new Runnable() {

            @Override
            public void run() {
                while(!stop) {
                    try {
                        blue += 5;
                        System.out.println(blue);
                        if(blue > 255) blue = 152;
                        Thread.sleep(20);
                        SwingUtilities.invokeLater(new Runnable() {

                            @Override
                            public void run() {
                                repaint();
                            }
                        });
                    } catch (InterruptedException ex) {
                        Logger.getLogger(loading.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                setVisible(false);
            }
        }).start();
    }
    
    public void animate1() {
        new Thread(new Runnable() {

            @Override
            public void run() {
                while(!stop) {
                    try {
                        x += 5;
                        System.out.println(x);
                        if(x > getWidth()) x = 0;
                        Thread.sleep(20);
                        SwingUtilities.invokeLater(new Runnable() {

                            @Override
                            public void run() {
                                setLocation(x, y);
                            }
                        });
                    } catch (InterruptedException ex) {
                        Logger.getLogger(loading.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                setVisible(false);
            }
        }).start();
    }
    
    @Override
    public void paint(Graphics g) {
        Graphics2D g2d = (Graphics2D)g;
        g2d.setColor(new Color(58,89,blue));
        g2d.fillRect(0, 0, getWidth(), getHeight());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
